name: build plugin

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - develop

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode package
      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ELDependenci-SQL
          path: ./eldependenci-sql-plugin/target/