env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Publish Process

# ↓ 移走 # 即可啟用自動生成 下載檔案 及 javadoc
on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v2
      - uses: eric2788/maven-jar-publish@v2
        with:
          java-version: 18
          body: 版本更新請到[這裏](https://eric2788.gitbook.io/eldependenci-sql/references/update/v0.0.6)查看。
          upload-module: './eldependenci-sql-plugin'
      - name: 'Update javadocs'
        id: update-javadoc
        uses: eric2788/push-javadoc-branch@main
        with:
          use-maven: true
          javadocs: "javadocs"
  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}