env:
  version: 0.0.5 # 你的版本名稱
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  plugin_name: "eldependenci-sql-plugin"

name: Publish Process

# ↓ 移走 # 即可啟用自動生成 下載檔案 及 javadoc
on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Delete tag and release
        id: delete-tag-release
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          tag_name: ${{ env.version }}
          delete_release: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ github.repository }}-${{ env.version }}
          body: |
            版本更新請到[這裏](https://eric2788.gitbook.io/eldependenci-sql/references/update/v0.0.5)查看。
          draft: false
          prerelease: false
      - name: Upload Release jar
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./${{ env.plugin_name }}/target/${{ env.plugin_name }}-${{env.version}}.jar # 請根據你插件名稱進行的修改
          asset_name: ${{ env.plugin_name }}-${{ env.version }}.jar # 請根據你插件名稱進行的修改
          asset_content_type: application/java-archive
      - name: 'Update javadocs'
        id: update-javadoc
        uses: eric2788/push-javadoc-branch@main
        with:
          use-maven: true
          javadocs: "javadocs"